"""baseline

Revision ID: f030b9e1c677
Revises: 
Create Date: 2026-07-03 07:41:39.946476+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f030b9e1c677'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_workspace_domain', sa.String(length=255), nullable=True),
    sa.Column('google_spreadsheet_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_usage_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage'))
    )
    op.create_index('ix_api_usage_tenant_id_measured_at', 'api_usage', ['tenant_id', 'measured_at'], unique=False)
    op.create_table('campaign_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('send_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('send_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('send_window_start', sa.Time(), nullable=False),
    sa.Column('send_window_end', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('unsubscribe_text', sa.Text(), nullable=False),
    sa.Column('executives_can_send', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_campaign_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_settings'))
    )
    op.create_index(op.f('ix_campaign_settings_tenant_id'), 'campaign_settings', ['tenant_id'], unique=True)
    op.create_table('integration_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('encrypted_secret_reference', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_integration_credentials_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_credentials')),
    sa.UniqueConstraint('tenant_id', 'provider', name=op.f('uq_integration_credentials_tenant_id'))
    )
    op.create_index(op.f('ix_integration_credentials_tenant_id'), 'integration_credentials', ['tenant_id'], unique=False)
    op.create_table('sheet_row_maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=255), nullable=False),
    sa.Column('tab', sa.String(length=100), nullable=False),
    sa.Column('row_key', sa.String(length=255), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sheet_row_maps_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_row_maps')),
    sa.UniqueConstraint('tenant_id', 'spreadsheet_id', 'tab', 'row_key', name=op.f('uq_sheet_row_maps_tenant_id'))
    )
    op.create_table('spreadsheet_sync_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sheet_tab', sa.String(length=100), nullable=False),
    sa.Column('row_key', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'synced', 'failed')", name=op.f('ck_spreadsheet_sync_events_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_spreadsheet_sync_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spreadsheet_sync_events'))
    )
    op.create_index('ix_spreadsheet_sync_events_tenant_id_created_at', 'spreadsheet_sync_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_spreadsheet_sync_events_tenant_id_sheet_tab_row_key', 'spreadsheet_sync_events', ['tenant_id', 'sheet_tab', 'row_key'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_suppressions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppressions'))
    )
    op.create_index('ix_suppressions_tenant_id_domain', 'suppressions', ['tenant_id', 'domain'], unique=False)
    op.create_index('ix_suppressions_tenant_id_email', 'suppressions', ['tenant_id', 'email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('google_oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'sales_manager', 'sales_executive', 'viewer')", name=op.f('ck_users_role_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('google_oauth_subject', name=op.f('uq_users_google_oauth_subject')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('validation_rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_validation_rule_sets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_rule_sets'))
    )
    op.create_index(op.f('ix_validation_rule_sets_tenant_id'), 'validation_rule_sets', ['tenant_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_id_created_at', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('data_source_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('compliance_posture', sa.String(length=10), nullable=False),
    sa.Column('access_method', sa.String(length=30), nullable=False),
    sa.Column('legal_note', sa.Text(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('requires_signoff', sa.Boolean(), nullable=False),
    sa.Column('signoff_user_id', sa.UUID(), nullable=True),
    sa.Column('signoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("access_method IN ('official_api', 'http_crawl', 'licensed_provider', 'serp', 'mock')", name=op.f('ck_data_source_configs_access_method_valid')),
    sa.CheckConstraint("compliance_posture IN ('green', 'amber', 'red')", name=op.f('ck_data_source_configs_compliance_posture_valid')),
    sa.CheckConstraint("source_name IN ('google_maps', 'company_websites', 'directories', 'yellow_pages', 'clutch', 'facebook_signals', 'serp_jobs', 'indeed', 'linkedin')", name=op.f('ck_data_source_configs_source_name_valid')),
    sa.ForeignKeyConstraint(['signoff_user_id'], ['users.id'], name=op.f('fk_data_source_configs_signoff_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_data_source_configs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source_configs')),
    sa.UniqueConstraint('tenant_id', 'source_name', name=op.f('uq_data_source_configs_tenant_id'))
    )
    op.create_index(op.f('ix_data_source_configs_tenant_id'), 'data_source_configs', ['tenant_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_email_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_email_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_templates'))
    )
    op.create_index(op.f('ix_email_templates_tenant_id'), 'email_templates', ['tenant_id'], unique=False)
    op.create_table('mining_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=255), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_km', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('company_size_min', sa.Integer(), nullable=True),
    sa.Column('company_size_max', sa.Integer(), nullable=True),
    sa.Column('contact_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclude_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('totals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'queued', 'running', 'paused', 'completed', 'failed', 'cancelled')", name=op.f('ck_mining_jobs_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mining_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_mining_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mining_jobs'))
    )
    op.create_index(op.f('ix_mining_jobs_created_by'), 'mining_jobs', ['created_by'], unique=False)
    op.create_index('ix_mining_jobs_tenant_id_created_at', 'mining_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_mining_jobs_tenant_id_status', 'mining_jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_template', sa.String(length=998), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('from_account', sa.String(length=320), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'scheduled', 'queued', 'sending', 'paused', 'completed', 'failed', 'cancelled')", name=op.f('ck_campaigns_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_campaigns_job_id_mining_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], name=op.f('fk_campaigns_template_id_email_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_campaigns_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_job_id'), 'campaigns', ['job_id'], unique=False)
    op.create_index('ix_campaigns_tenant_id_created_at', 'campaigns', ['tenant_id', 'created_at'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('google_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('google_reviews', sa.Integer(), nullable=True),
    sa.Column('facebook_page_url', sa.String(length=1000), nullable=True),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=500), nullable=True),
    sa.Column('dedupe_status', sa.String(length=50), nullable=False),
    sa.Column('website_status', sa.String(length=50), nullable=True),
    sa.Column('hiring_signal_status', sa.String(length=50), nullable=True),
    sa.Column('compliance_posture', sa.String(length=10), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_companies_job_id_mining_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_companies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_dedupe_key'), 'companies', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_companies_google_place_id'), 'companies', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_companies_job_id'), 'companies', ['job_id'], unique=False)
    op.create_index('ix_companies_tenant_id_created_at', 'companies', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_companies_tenant_id_domain', 'companies', ['tenant_id', 'domain'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("format IN ('csv', 'xlsx', 'json')", name=op.f('ck_export_jobs_format_valid')),
    sa.CheckConstraint("status IN ('draft', 'queued', 'running', 'paused', 'completed', 'failed', 'cancelled')", name=op.f('ck_export_jobs_status_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_export_jobs_job_id_mining_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_export_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs'))
    )
    op.create_index(op.f('ix_export_jobs_job_id'), 'export_jobs', ['job_id'], unique=False)
    op.create_index('ix_export_jobs_tenant_id_created_at', 'export_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('resolving_location', 'discovering', 'deduping', 'crawling', 'extracting', 'enriching', 'validating', 'syncing', 'sales_ready', 'done')", name=op.f('ck_job_events_stage_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_job_events_job_id_mining_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events')),
    sa.UniqueConstraint('seq', name=op.f('uq_job_events_seq'))
    )
    op.create_index('ix_job_events_job_id_seq', 'job_events', ['job_id', 'seq'], unique=False)
    op.create_table('source_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('access_method', sa.String(length=30), nullable=False),
    sa.Column('compliance_posture', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("access_method IN ('official_api', 'http_crawl', 'licensed_provider', 'serp', 'mock')", name=op.f('ck_source_runs_access_method_valid')),
    sa.CheckConstraint("compliance_posture IN ('green', 'amber', 'red')", name=op.f('ck_source_runs_compliance_posture_valid')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name=op.f('ck_source_runs_status_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_source_runs_job_id_mining_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_runs'))
    )
    op.create_index(op.f('ix_source_runs_job_id'), 'source_runs', ['job_id'], unique=False)
    op.create_table('company_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('access_method', sa.String(length=30), nullable=False),
    sa.Column('compliance_posture', sa.String(length=10), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("access_method IN ('official_api', 'http_crawl', 'licensed_provider', 'serp', 'mock')", name=op.f('ck_company_sources_access_method_valid')),
    sa.CheckConstraint("compliance_posture IN ('green', 'amber', 'red')", name=op.f('ck_company_sources_compliance_posture_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_sources_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_sources'))
    )
    op.create_index(op.f('ix_company_sources_company_id'), 'company_sources', ['company_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('role_category', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1000), nullable=True),
    sa.Column('facebook_url', sa.String(length=1000), nullable=True),
    sa.Column('source_page', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('primary_contact', sa.Boolean(), nullable=False),
    sa.Column('enrichment_status', sa.String(length=20), nullable=False),
    sa.Column('enrichment_provider', sa.String(length=100), nullable=True),
    sa.Column('final_email_status', sa.String(length=30), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_ready', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("enrichment_status IN ('not_needed', 'pending', 'enriched', 'no_result', 'failed')", name=op.f('ck_contacts_enrichment_status_valid')),
    sa.CheckConstraint("final_email_status IN ('VERIFIED', 'INVALID_SYNTAX', 'DISPOSABLE_REJECTED', 'ROLE_BASED_REJECTED', 'MX_FAILED', 'LLM_LOW_CONFIDENCE', 'PROVIDER_INVALID', 'CATCH_ALL_REVIEW', 'RISK_REVIEW', 'UNKNOWN_RETRY', 'SUPPRESSED')", name=op.f('ck_contacts_final_email_status_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_contacts_job_id_mining_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_contacts_owner_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_contacts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_job_id'), 'contacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_contacts_owner_user_id'), 'contacts', ['owner_user_id'], unique=False)
    op.create_index('ix_contacts_tenant_id_created_at', 'contacts', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_contacts_tenant_id_email', 'contacts', ['tenant_id', 'email'], unique=False)
    op.create_table('data_source_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('source_run_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('access_method', sa.String(length=30), nullable=False),
    sa.Column('compliance_posture', sa.String(length=10), nullable=False),
    sa.Column('url_or_endpoint', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("access_method IN ('official_api', 'http_crawl', 'licensed_provider', 'serp', 'mock')", name=op.f('ck_data_source_audit_events_access_method_valid')),
    sa.CheckConstraint("compliance_posture IN ('green', 'amber', 'red')", name=op.f('ck_data_source_audit_events_compliance_posture_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_data_source_audit_events_job_id_mining_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_run_id'], ['source_runs.id'], name=op.f('fk_data_source_audit_events_source_run_id_source_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_data_source_audit_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source_audit_events'))
    )
    op.create_index(op.f('ix_data_source_audit_events_job_id'), 'data_source_audit_events', ['job_id'], unique=False)
    op.create_index('ix_data_source_audit_events_tenant_id_created_at', 'data_source_audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('hiring_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description_excerpt', sa.Text(), nullable=True),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("signal_type IN ('job_posting', 'careers_page', 'public_post')", name=op.f('ck_hiring_signals_signal_type_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_hiring_signals_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hiring_signals'))
    )
    op.create_index(op.f('ix_hiring_signals_company_id'), 'hiring_signals', ['company_id'], unique=False)
    op.create_table('email_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_email_candidates_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_candidates'))
    )
    op.create_index(op.f('ix_email_candidates_contact_id'), 'email_candidates', ['contact_id'], unique=False)
    op.create_index(op.f('ix_email_candidates_email'), 'email_candidates', ['email'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'sent', 'delivered', 'opened', 'clicked', 'replied', 'hard_bounce', 'soft_bounce', 'blocked', 'spam_complaint', 'unsubscribed')", name=op.f('ck_email_messages_status_valid')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_messages_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_email_messages_contact_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages'))
    )
    op.create_index('ix_email_messages_campaign_id_status', 'email_messages', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_email_messages_contact_id'), 'email_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_email_messages_gmail_message_id'), 'email_messages', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_to_email'), 'email_messages', ['to_email'], unique=False)
    op.create_table('sales_ready_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_summary', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('campaign_status', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('sales_notes', sa.Text(), nullable=True),
    sa.Column('tombstoned', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sales_ready_leads_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_sales_ready_leads_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['mining_jobs.id'], name=op.f('fk_sales_ready_leads_job_id_mining_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sales_ready_leads_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_ready_leads'))
    )
    op.create_index(op.f('ix_sales_ready_leads_contact_id'), 'sales_ready_leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_sales_ready_leads_job_id'), 'sales_ready_leads', ['job_id'], unique=False)
    op.create_index('ix_sales_ready_leads_tenant_id_created_at', 'sales_ready_leads', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_sales_ready_leads_tenant_id_email', 'sales_ready_leads', ['tenant_id', 'email'], unique=False)
    op.create_table('bounce_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('smtp_status_code', sa.String(length=20), nullable=True),
    sa.Column('bounce_type', sa.String(length=20), nullable=False),
    sa.Column('diagnostic_code', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('raw_message_reference', sa.String(length=500), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("bounce_type IN ('hard', 'soft', 'mailbox_full', 'invalid_domain', 'blocked', 'spam_rejected', 'rate_limited', 'unknown')", name=op.f('ck_bounce_events_bounce_type_valid')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_bounce_events_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], name=op.f('fk_bounce_events_email_message_id_email_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounce_events'))
    )
    op.create_index(op.f('ix_bounce_events_email'), 'bounce_events', ['email'], unique=False)
    op.create_index(op.f('ix_bounce_events_email_message_id'), 'bounce_events', ['email_message_id'], unique=False)
    op.create_table('reply_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_reply_events_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], name=op.f('fk_reply_events_email_message_id_email_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reply_events'))
    )
    op.create_index(op.f('ix_reply_events_email_message_id'), 'reply_events', ['email_message_id'], unique=False)
    op.create_table('validation_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_candidate_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('syntax_status', sa.String(length=20), nullable=False),
    sa.Column('disposable_status', sa.String(length=20), nullable=False),
    sa.Column('role_based_status', sa.String(length=20), nullable=False),
    sa.Column('mx_status', sa.String(length=20), nullable=False),
    sa.Column('llm_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('llm_reason', sa.Text(), nullable=True),
    sa.Column('millionverifier_status', sa.String(length=20), nullable=True),
    sa.Column('final_status', sa.String(length=30), nullable=True),
    sa.Column('final_reason', sa.Text(), nullable=True),
    sa.Column('raw_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("disposable_status IN ('pass', 'fail', 'review', 'skipped', 'pending')", name=op.f('ck_validation_checks_disposable_status_valid')),
    sa.CheckConstraint("final_status IN ('VERIFIED', 'INVALID_SYNTAX', 'DISPOSABLE_REJECTED', 'ROLE_BASED_REJECTED', 'MX_FAILED', 'LLM_LOW_CONFIDENCE', 'PROVIDER_INVALID', 'CATCH_ALL_REVIEW', 'RISK_REVIEW', 'UNKNOWN_RETRY', 'SUPPRESSED')", name=op.f('ck_validation_checks_final_status_valid')),
    sa.CheckConstraint("millionverifier_status IN ('valid', 'invalid', 'catch_all', 'risk', 'unknown')", name=op.f('ck_validation_checks_millionverifier_status_valid')),
    sa.CheckConstraint("mx_status IN ('pass', 'fail', 'review', 'skipped', 'pending')", name=op.f('ck_validation_checks_mx_status_valid')),
    sa.CheckConstraint("role_based_status IN ('pass', 'fail', 'review', 'skipped', 'pending')", name=op.f('ck_validation_checks_role_based_status_valid')),
    sa.CheckConstraint("syntax_status IN ('pass', 'fail', 'review', 'skipped', 'pending')", name=op.f('ck_validation_checks_syntax_status_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_validation_checks_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_validation_checks_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_candidate_id'], ['email_candidates.id'], name=op.f('fk_validation_checks_email_candidate_id_email_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_checks'))
    )
    op.create_index(op.f('ix_validation_checks_contact_id'), 'validation_checks', ['contact_id'], unique=False)
    op.create_index(op.f('ix_validation_checks_email_candidate_id'), 'validation_checks', ['email_candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_checks_email_candidate_id'), table_name='validation_checks')
    op.drop_index(op.f('ix_validation_checks_contact_id'), table_name='validation_checks')
    op.drop_table('validation_checks')
    op.drop_index(op.f('ix_reply_events_email_message_id'), table_name='reply_events')
    op.drop_table('reply_events')
    op.drop_index(op.f('ix_bounce_events_email_message_id'), table_name='bounce_events')
    op.drop_index(op.f('ix_bounce_events_email'), table_name='bounce_events')
    op.drop_table('bounce_events')
    op.drop_index('ix_sales_ready_leads_tenant_id_email', table_name='sales_ready_leads')
    op.drop_index('ix_sales_ready_leads_tenant_id_created_at', table_name='sales_ready_leads')
    op.drop_index(op.f('ix_sales_ready_leads_job_id'), table_name='sales_ready_leads')
    op.drop_index(op.f('ix_sales_ready_leads_contact_id'), table_name='sales_ready_leads')
    op.drop_table('sales_ready_leads')
    op.drop_index(op.f('ix_email_messages_to_email'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_gmail_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_contact_id'), table_name='email_messages')
    op.drop_index('ix_email_messages_campaign_id_status', table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_email_candidates_email'), table_name='email_candidates')
    op.drop_index(op.f('ix_email_candidates_contact_id'), table_name='email_candidates')
    op.drop_table('email_candidates')
    op.drop_index(op.f('ix_hiring_signals_company_id'), table_name='hiring_signals')
    op.drop_table('hiring_signals')
    op.drop_index('ix_data_source_audit_events_tenant_id_created_at', table_name='data_source_audit_events')
    op.drop_index(op.f('ix_data_source_audit_events_job_id'), table_name='data_source_audit_events')
    op.drop_table('data_source_audit_events')
    op.drop_index('ix_contacts_tenant_id_email', table_name='contacts')
    op.drop_index('ix_contacts_tenant_id_created_at', table_name='contacts')
    op.drop_index(op.f('ix_contacts_owner_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_job_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_sources_company_id'), table_name='company_sources')
    op.drop_table('company_sources')
    op.drop_index(op.f('ix_source_runs_job_id'), table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index('ix_job_events_job_id_seq', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_export_jobs_tenant_id_created_at', table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_job_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index('ix_companies_tenant_id_domain', table_name='companies')
    op.drop_index('ix_companies_tenant_id_created_at', table_name='companies')
    op.drop_index(op.f('ix_companies_job_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_google_place_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_dedupe_key'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_campaigns_tenant_id_created_at', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_job_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_mining_jobs_tenant_id_status', table_name='mining_jobs')
    op.drop_index('ix_mining_jobs_tenant_id_created_at', table_name='mining_jobs')
    op.drop_index(op.f('ix_mining_jobs_created_by'), table_name='mining_jobs')
    op.drop_table('mining_jobs')
    op.drop_index(op.f('ix_email_templates_tenant_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_data_source_configs_tenant_id'), table_name='data_source_configs')
    op.drop_table('data_source_configs')
    op.drop_index('ix_audit_logs_tenant_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_validation_rule_sets_tenant_id'), table_name='validation_rule_sets')
    op.drop_table('validation_rule_sets')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_suppressions_tenant_id_email', table_name='suppressions')
    op.drop_index('ix_suppressions_tenant_id_domain', table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index('ix_spreadsheet_sync_events_tenant_id_sheet_tab_row_key', table_name='spreadsheet_sync_events')
    op.drop_index('ix_spreadsheet_sync_events_tenant_id_created_at', table_name='spreadsheet_sync_events')
    op.drop_table('spreadsheet_sync_events')
    op.drop_table('sheet_row_maps')
    op.drop_index(op.f('ix_integration_credentials_tenant_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_campaign_settings_tenant_id'), table_name='campaign_settings')
    op.drop_table('campaign_settings')
    op.drop_index('ix_api_usage_tenant_id_measured_at', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_table('tenants')
    # ### end Alembic commands ###
